service: my-blog
app: my-blog
tenant: equimper

provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  subscribe:
    handler: handler.subscribe
    events:
      - http:
          path: api/mailchimp/subscribe
          method: post
          cors:
            - enabled: true
              origin: "https://equimper.com"
              headers: "Content-Type,application/json"
              methods: "POST"
